@extends('errors.layout')
@section('title', 'Halaman Tidak Ditemukan')
@section('code', '404')
@section('message', 'Oops! Halaman Hilang')
@section('description', 'Maaf, halaman yang Anda cari tidak dapat ditemukan atau telah dipindahkan.')